# Generated by Django 4.2.5 on 2023-09-16 02:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blogcategory_blogs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_filename),
        ),
    ]
