# Generated by Django 4.2.5 on 2023-09-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_image_blog_date_blog_stt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
